server:
  port: 8080
spring:
  application:
    name: interior
  datasource:
    username: "microservices"
    url: jdbc:postgresql://localhost:5432/interior
    password: "password"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: localhost:5672
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
