spring:
  application:
    name: gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    loadbalancer:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: finance
          uri: lb://finance
          predicates:
            - Path=/api/finance/**
          filters:
            - RewritePath=/api/finance/(?<path>.*), /$\{path}
        - id: interior
          uri: lb://interior
          predicates:
            - Path=/api/v1/interior/**
          filters:
            - RewritePath=/api/v1/interior/(?<path>.*), /$\{path}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"