server:
  port: 9001

spring:
  application:
    name: finance
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: mongodb://localhost:27017/finance?retryWrites=true&w=majority
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

#management.endpoints.web.exposure.include= *
#spring.application.name=interior-service
#spring.config.import=optional:configserver:http://localhost:8088
#eureka.instance.instance-id=${spring.application.name}:${random.uuid}
#server.port=9002
#
#spring.rabbitmq.host=rat.rmq2.cloudamqp.com
#spring.rabbitmq.username=ezryqhbz
#spring.rabbitmq.password=UpmtRpp7rpsB--FN5IQvgG1IXoxjz9VR
#spring.rabbitmq.virtual-host=ezryqhbz
#
#spring.cloud.config.failFast= true
