apiVersion: apps/v1
kind: Deployment
metadata:
  name: interior
  labels:
    app: interior
spec:
  replicas: 1
  template:
    metadata:
      name: interior
      labels:
        app: interior
    spec:
      containers:
        - name: interior
          image: lisno/interior:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: interior
