apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance
  labels:
    app: finance
spec:
  replicas: 1
  template:
    metadata:
      name: finance
      labels:
        app: finance
    spec:
      containers:
        - name: finance

          image: lisno/finance:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: finance
